##### Forbidden temporal predicate must not be used (e.g. BFO_0000176)

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?p WHERE {
  ?s ?p ?o .
  FILTER(STRSTARTS(STR(?p), "http://purl.obolibrary.org/obo/BFO_"))

  FILTER NOT EXISTS {
    SERVICE <http://matwerk-virtuoso:8890/sparql> {
      GRAPH <https://nfdi.fiz-karlsruhe.de/matwerk/bfo-2020-without-some-all-times> {
        ?p a owl:ObjectProperty .
      }
    }
  }
}