##### Deprecated term must not be used (owl:deprecated true)

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?s ?iri WHERE {
  ?s ?p ?o .
  FILTER(?p NOT IN (rdfs:subClassOf, rdfs:subPropertyOf, rdfs:domain, rdfs:range,
                  owl:equivalentClass, owl:equivalentProperty, owl:disjointWith,
                  owl:inverseOf, <http://rdfs.org/ns/void#class>))

  # Any IRI occurring as predicate or object (or subject, if you want)
  VALUES ?iriRole { "p" "o" }
  BIND(IF(?iriRole="p", ?p, ?o) AS ?iri)

  FILTER(isIRI(?iri))
  ?iri owl:deprecated true .

}