name: shacl validation

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main 
    - name: Validate entire knowledge graph data against SHACL shapes 
      run: |
           # retrieve complete KG
           curl -v https://nfdi.fiz-karlsruhe.de/matwerk/sparql --data query='CONSTRUCT {%0A%20 %3Fs %3Fp %3Fo .%0A}%0AWHERE {%0A%20 %3Fs %3Fp %3Fo .%0A}%0A' -H "accept: text/turtle"  > matwerk.ttl

           pip install pyshacl

           #curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
           #java -jar robot.jar --version

           #java -jar robot.jar reason  --catalog main/catalog-v001.xml --reasoner elk --input main/shapes/shape1-data.ttl --output shape1-data-reasoned.ttl

           python3 -m pyshacl  -s main/shapes/shape1.ttl matwerk.ttl
